[package]
name = "mprove-nova"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bellperson = "0.25"
neptune = "10.0.0"
curve25519-dalek = { git = "https://github.com/varunthakore/curve25519-dalek.git", branch = "release/3.2" }
sha2 = { version = "0.9", default-features = false }
sha3 = { version = "0.9", default-features = false }
ff = "0.13"
bp-ed25519 = { git = "https://github.com/avras/bp-ed25519.git"}
merkle-trees = { git = "https://github.com/varunthakore/merkle-trees.git" }
crypto-bigint = "0.5.2"
num-bigint = "0.4.3"
nova-snark = "0.22.0"
itertools = "0.11.0"
rand_07 = { package = "rand", version = "0.7"}
rand = "0.8.5"
hex = "0.4.3"
clap = "4.1.8"

[dev-dependencies]
bincode = "1.3.3"
clap = "4.1.8"
flate2 = "1.0.25"
pasta_curves = "0.5.1"
generic-array = "0.14.6"

[[bin]]
name = "gen_values"
path = "src/gen_values/main.rs"
